---
# This playbook will install mysql

- name: Installing Mysql 5.6
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server-5.6
   - mysql-client-5.6
  when: mysql_version == "5.6" and ansible_distribution_version == "14.04"
  tags: mysql

- name: Installing MySQL 5.6 on Ubuntu 12.04
  apt_repository: repo='ppa:ondrej/mysql-5.6' state=present
  when: mysql_version == "5.6" and ansible_distribution_version == "12.04"
  tags: mysql

- name: Installing MySQL 5.6 on Ubuntu 12.04
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - mysql-client
  when: mysql_version == "5.6" and ansible_distribution_version == "12.04"
  tags: mysql

- name: Configure Mysql 5.6
  template: src=my-5.6.cnf.j2 dest=/etc/mysql/my.cnf backup=true
  when: mysql_version == "5.6"
  notify:
  - Reload mysql
  tags: mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=true
  tags: mysql

#- name: Install the Python MySQLB module
#  pip: name=MySQL-python

#- name: update mysql root password for all root accounts
#  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
#  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost
#  tags: mysql