---
- hosts: all
  sudo: true
  vars:
     document_root: /vagrant
     mysql_version: "5.6"
     mysql_root_password: "root"
  pre_tasks:
     - name: update apt cache
       apt: update_cache=yes
  roles:
     - ansible-pip-master
     - common
     - webserver
     - database